# Generated by Django 4.2.2 on 2023-07-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe una categoria con este nombre'}, max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe una marca con este nombre'}, max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.categoria', verbose_name='Categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('placa', models.AutoField(primary_key=True, serialize=False, verbose_name='Placa')),
                ('serial', models.CharField(error_messages={'unique': 'Ya existe un elemento con este serial'}, max_length=50, unique=True, verbose_name='Serial')),
                ('estado', models.CharField(default='Por asignar', max_length=50, verbose_name='Estado')),
                ('IP', models.GenericIPAddressField(blank=True, error_messages={'unique': 'La IP está en uso'}, null=True, unique=True, verbose_name='IP')),
                ('MAC', models.CharField(error_messages={'unique': 'Ya existe un elemento con esta MAC'}, max_length=50, unique=True, verbose_name='MAC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='admin', max_length=50, verbose_name='Creado por')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personas.proveedores', verbose_name='Proveedor')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.referencia', verbose_name='Referencia')),
            ],
        ),
    ]
