# Generated by Django 4.2.2 on 2023-08-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemento',
            options={'verbose_name': 'Elemento', 'verbose_name_plural': 'Elementos'},
        ),
    ]
