# Generated by Django 4.2.2 on 2023-08-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_elemento_delete_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='placa',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Placa'),
        ),
    ]
