# Generated by Django 4.2.2 on 2023-08-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_alter_elemento_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
