# Generated by Django 4.2.2 on 2023-08-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_elemento_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elemento',
            old_name='tipo',
            new_name='modelo',
        ),
    ]
