# Generated by Django 4.2.2 on 2023-08-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0007_alter_elemento_mac'),
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.funcionario')),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=10)),
                ('timestamps', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('fechaFin', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=50000)),
                ('observaciones', models.CharField(max_length=50000)),
                ('timestamps', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(default='En Progreso', max_length=100)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.elemento')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.asignacion')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.elemento')),
            ],
            options={
                'verbose_name': 'DetallesAsignacion',
                'verbose_name_plural': 'DetallesAsignaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizado', models.BooleanField(default=True)),
                ('timestamps', models.DateTimeField(auto_now=True)),
                ('fechaBorrado', models.DateField()),
                ('baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.baja')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.elemento')),
            ],
        ),
    ]
