# Generated by Django 4.2.2 on 2023-07-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('NIT', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('razonSocial', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('iden', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('status', models.CharField(default='Activo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empresa.sede')),
            ],
        ),
    ]
